version: '3.9'
services:
  payments_app:
    container_name: payments_app
    image: payments_app:1.0.0
    build: .
    environment:
      DATABASE_URL: "host=payments_db user=postgres password=postgres dbname=payments_db sslmode=disable TimeZone=UTC"
    ports:
      - "8000:8000"
    depends_on:
      - payments_db
    networks:
      - payments_network
  payments_db:
    container_name: payments_db
    image: postgres:15-alpine
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: payments_db
    ports:
      - "5432:5432"
    volumes:
      - ./migration/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migration/seeds/seeds.sql:/migration/seeds/seeds.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - payments_network

volumes:
  postgres-data:

networks:
  payments_network: