apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood_app-deployment
  labels:
    app: fastfood_app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastfood_app-deployment
  template:
    metadata:
      labels:
        app: fastfood_app-deployment
    spec:
      containers:
        - name: container-fastfood_app-deployment
          image: joaocampari/postech-soat2-grupo16:1.0.0
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10