apiVersion: v1
kind: Pod
metadata:
  name: fastfood_db
  labels:
    app: fastfood_db
spec:
  containers:
    - name: fastfood_db
      image: postgres:15
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: configmap-fastfood_db
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: configmap-fastfood_db
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: configmap-fastfood_db
              key: POSTGRES_DB