apiVersion: v1
kind: Pod
metadata:
  name: fastfood_app
  labels:
    app: fastfood_app
spec:
  containers:
    - name: fastfood_app
      image: joaocampari/postech-soat2-grupo16:1.0.0
      ports:
        - containerPort: 8000
      env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: configmap-fastfood_db
              key: DATABASE_URL