name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5

      - name: Install dependencies
        run: go get -d -v ./...

      - name: Build
        run: go build -o build .

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fastfood_db
        options: >-
          --mount type=bind,source=$(GITHUB_WORKSPACE)/docker-entrypoint-initdb.d,target=/docker-entrypoint-initdb.d
          --mount type=bind,source=$(GITHUB_WORKSPACE)/migration/seeds,target=/migration/seeds

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5

      - name: Install dependencies
        run: go get -d -v ./...

      - name: Wait for Postgres to start
        run: |
          while ! nc -z localhost 5432; do sleep 1; done

      - name: Test
        run: go test -v ./...

      - name: Show Postgres logs
        run: docker logs postgres


